config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#landing_page"


  resources :cars do
    resources :reviews, only: [:create]
    resources :favourites, only: [:create]
  end

  resources :favourites, only: [:index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner

  has_many :reviews
  has_many :favourites

  validates :brand, presence: true
  validates :model, presence: true
  validates :year, presence: true,  numericality: { only_integer: true }
  validates :fuel, presence: true

end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :car
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :cars
  has_one_attached :profile_picture

  validates :nickname, uniqueness: true, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car

  validates :comment, presence: true
  validates :rating, presence: true,  numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
    @review = Review.new
    @favourite = Favourite.new
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

  def index
    @favourites = Favourite.all
  end

  def create
    @favourite = Favourite.new
    car = Car.find(params['car_id'])
    @favourite.car = car

    if @favourite.save
      redirect_to car_path(car)
    else
      render 'cars/show', status: :unprocessable_entity
    end
  end

  def destroy
    @favourite = Favourite.find(params['id'])
    @favourite.destroy
    redirect_to favourites_path, status: :see_other
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing_page
    
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @car = Car.find(params["car_id"])
    @review.car = @car

    if @review.save
      redirect_to car_path(@car)
    else
      render 'cars/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cars/_car.html.erb
<div class="card-trip">
  <div class="card-trip-top">
    <h2><%= car.brand %></h2>
    <h3><%= car.model %></h3>
    <p><%= car.created_at.strftime("%a %b %e at %l:%M %p") %></p>
  </div>
  <%= link_to car_path(car) do %>
    <%= image_tag car.image_url %>
  <% end %>
  <div class="card-trip-infos">
    <%= link_to car_path(car) do %>
      <h2><i class="fa-regular fa-comment"></i> Comment </h2>
    <% end %>
    <div class="owner-name">
      <%= car.owner.nickname %>
    </div>
  </div>
</div>

app/views/cars/index.html.erb
<%= render 'shared/navbar' %>

<div class="container">
  <div class="wrapper">
    <% @cars.each do |car| %>
      <%= render 'car', car: car %>
    <% end %>
  </div>

</div>

app/views/cars/show.html.erb
<%= render 'shared/navbar' %>

<div class="container">
  <div class="wrapper">

    <div class="show-car">
      <%= image_tag @car.image_url %>

      <div class="show-car-middle">
        <div class="show-car-info">
          <h2><%= @car.brand %></h2>
          <h3><%= @car.model %></h3>
          <p><%= @car.fuel %></p>
          <p><%= @car.year %></p>
          <div class="favourite-btn">
            <% if @car.favourites.empty? %>
              <%= simple_form_for [@car, @favourite] do |f| %>
                <%= f.submit 'Save in my Garage', class: "btn btn-danger" %>
              <% end %>
            <% else %>
              <p>This car is parked in your garage!</p>
            <% end %>
          </div>
        </div>


        <div class="reviews-form">
          <%= simple_form_for [@car, @review] do |f|%>
            <%= f.input :comment, label: false, placeholder: "Comment here.." %>
              <%= f.input :rating, collection: 0..5, label: false %>
              <%= f.submit 'Send' %>
          <% end %>
        </div>

      </div>

    <div class="reviews-list">
      <hr>
      <% @car.reviews.each do |review| %>
        <p><%= review.comment %></p>
        <p><%= '⭐️' * review.rating %></p>
        <hr>
      <% end %>
    </div>

    </div>
  </div>

</div>

app/views/favourites/favourites.html.erb
<%= render 'shared/navbar' %>
<div class="container">
  <div class="wrapper w-75">
    <h2>My Garage</h2>
    <% @favourites.each do |favourite| %>
      <div class="card-product">
        <%= image_tag favourite.car.image_url %>
        <div class="card-product-infos">
          <div>
            <h2><%= favourite.car.brand %></h2>
            <h3><%= favourite.car.model %></h3>
            <p><%= favourite.car.year %> | <%= favourite.car.fuel %></p>
          </div>
          <%= link_to favourite_path(favourite), data: {turbo_method: :delete, turbo_confirm: "Do you really want to take the #{favourite.car.model} out of your garage?"} do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
      </div>



  <% end %>
  </div>
</div>

app/views/favourites/index.html.erb
<%= render 'shared/navbar' %>
<div class="container">
  <div class="wrapper w-75">
    <h2>My Garage</h2>
    <% @favourites.each do |favourite| %>
      <div class="card-product">
        <%= image_tag favourite.car.image_url %>
        <div class="card-product-infos">
          <div>
            <h2><%= favourite.car.brand %></h2>
            <h3><%= favourite.car.model %></h3>
            <p><%= favourite.car.year %> | <%= favourite.car.fuel %></p>
          </div>
          <%= link_to favourite_path(favourite), data: {turbo_method: :delete, turbo_confirm: "Do you really want to take the #{favourite.car.model} out of your garage?"} do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
      </div>



  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAwesomeGarage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/landing_page.html.erb
<div class="banner-wrapper">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1504078151140-0d07249b8a9a?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
    <div class="container text-center">
      <h1>Awesome Garage</h1>
      <p>Your personal garage with the cars of your dreams</p>
      <%# <a class="btn btn-flat" href="#">Start here</a> %>
      <%= link_to "Start here", cars_path, class: "btn btn-flat" %>
      <%=  %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="d-flex align-items-center">
    <%= image_tag 'https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png' %>
    <h1>Awesome Garage</h1>
  </div>
  <div>
    <%= link_to 'Home', cars_path %>
    <%= link_to 'My Garage', favourites_path %>
  </div>
</div>